package com.copynet.videotoolshub;
import android.app.*;import android.os.*;import android.content.*;import android.content.SharedPreferences;import android.graphics.*;import android.net.*;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 static class Tool{String n,l,s,d,c,u,b,x;Tool(String n,String l,String s,String d,String c,String u,String b,String x){this.n=n;this.l=l;this.s=s;this.d=d;this.c=c;this.u=u;this.b=b;this.x=x;}}
 final List<Tool> tools=Arrays.asList(
 new Tool("Dreamina","D","ساخت ویدئو با Seedance","اعتبار رایگان روزانه و بدون پرداخت اولیه","ساخت ویدئو","https://dreamina.capcut.com/","رایگان روزانه","پیشنهاد اصلی پروژه"),
 new Tool("Kling AI","K","متن و عکس به ویدئو","اعتبار رایگان؛ ممکن است صف ساخت طولانی‌تر باشد","ساخت ویدئو","https://app.klingai.com/global/","اعتبار رایگان","کیفیت حرکت خوب"),
 new Tool("PixVerse","P","کلیپ از عکس و متن","اعتبار رایگان روزانه؛ خروجی رایگان ممکن است واترمارک داشته باشد","ساخت ویدئو","https://app.pixverse.ai/","رایگان روزانه","تست سریع"),
 new Tool("Hailuo AI","H","ویدئو با MiniMax","اعتبار خوش‌آمدگویی یا آزمایشی؛ مقدار آن ممکن است تغییر کند","ساخت ویدئو","https://hailuoai.video/create","آزمایشی رایگان","اعتبار را قبل ساخت ببین"),
 new Tool("CapCut","C","تدوین و مونتاژ نهایی","چسباندن سکانس‌ها، صدا، زیرنویس و خروجی ریلز","ویرایش","https://www.capcut.com/","ابزار رایگان","برای مرحله نهایی"));
 LinearLayout list;EditText search;String cat="همه";SharedPreferences pref;TextView count;
 int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}TextView t(String v,float s,int c,boolean b){TextView x=new TextView(this);x.setText(v);x.setTextSize(s);x.setTextColor(c);x.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);x.setTypeface(Typeface.create("sans",b?1:0));return x;}
 public void onCreate(Bundle z){super.onCreate(z);pref=getSharedPreferences("fav",0);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundResource(R.drawable.bg_app);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setPadding(dp(18),dp(22),dp(18),dp(28));sc.addView(r);
 LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView logo=t("▶",25,Color.WHITE,true);logo.setGravity(17);logo.setBackgroundResource(R.drawable.bg_circle_icon);logo.setLayoutParams(new LinearLayout.LayoutParams(dp(60),dp(60)));h.addView(logo);LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(dp(14),0,0,0);ht.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));ht.addView(t("Video Tools Hub AI",25,Color.WHITE,true));TextView ss=t("ابزارهای رایگان برای پروژه‌های ویدئویی",14,Color.rgb(183,203,230),false);ss.setPadding(0,dp(5),0,0);ht.addView(ss);h.addView(ht);r.addView(h);
 TextView route=t("مسیر پیشنهادی: Dreamina / Seedance  ←  CapCut",15,Color.WHITE,true);route.setPadding(dp(16),dp(15),dp(16),dp(15));route.setBackgroundResource(R.drawable.bg_card);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(20),0,dp(12));route.setLayoutParams(rp);r.addView(route);
 search=new EditText(this);search.setHint("جست‌وجوی ابزار یا کاربرد...");search.setSingleLine();search.setTextColor(Color.WHITE);search.setHintTextColor(Color.rgb(134,158,190));search.setTextSize(15);search.setBackgroundResource(R.drawable.bg_search);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(55));sp.setMargins(0,dp(5),0,dp(10));search.setLayoutParams(sp);r.addView(search);
 HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);LinearLayout cats=new LinearLayout(this);cats.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);for(String c:new String[]{"همه","ساخت ویدئو","ویرایش","علاقه‌مندی"}){TextView q=t(c,14,Color.WHITE,true);q.setGravity(17);q.setBackgroundResource(R.drawable.bg_chip);q.setSelected(c.equals("همه"));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(42));cp.setMargins(dp(5),0,dp(5),0);q.setPadding(dp(16),0,dp(16),0);q.setLayoutParams(cp);q.setOnClickListener(v->{cat=c;for(int i=0;i<cats.getChildCount();i++)cats.getChildAt(i).setSelected(cats.getChildAt(i)==v);render();});cats.addView(q);}hsv.addView(cats);r.addView(hsv);
 LinearLayout sh=new LinearLayout(this);sh.setGravity(Gravity.CENTER_VERTICAL);sh.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout.LayoutParams shp=new LinearLayout.LayoutParams(-1,-2);shp.setMargins(0,dp(18),0,dp(4));sh.setLayoutParams(shp);TextView st=t("ابزارهای پیشنهادی",20,Color.WHITE,true);st.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));count=t("",13,Color.rgb(155,178,210),false);sh.addView(st);sh.addView(count);r.addView(sh);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);TextView foot=t("وضعیت اعتبار رایگان ممکن است با زمان، منطقه و نوع حساب تغییر کند؛ موجودی اعتبار را داخل همان سایت بررسی کن.",12,Color.rgb(131,153,184),false);foot.setPadding(dp(8),dp(18),dp(8),0);r.addView(foot);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render();}public void afterTextChanged(Editable e){}});setContentView(sc);render();}
 void render(){list.removeAllViews();String q=search.getText().toString().trim().toLowerCase(Locale.ROOT);int n=0;for(Tool x:tools){boolean f=pref.getBoolean(x.n,false);boolean ok=cat.equals("همه")||cat.equals(x.c)||(cat.equals("علاقه‌مندی")&&f);String h=(x.n+x.s+x.d+x.b).toLowerCase(Locale.ROOT);if(!ok||(!q.isEmpty()&&!h.contains(q)))continue;list.addView(card(x));n++;}count.setText(n+" ابزار");}
 View card(Tool x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackgroundResource(R.drawable.bg_card);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView ic=t(x.l,23,Color.WHITE,true);ic.setGravity(17);ic.setBackgroundResource(R.drawable.bg_circle_icon);ic.setLayoutParams(new LinearLayout.LayoutParams(dp(52),dp(52)));top.addView(ic);LinearLayout inf=new LinearLayout(this);inf.setOrientation(LinearLayout.VERTICAL);inf.setPadding(dp(12),0,dp(8),0);inf.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));inf.addView(t(x.n,19,Color.WHITE,true));TextView su=t(x.s,14,Color.rgb(186,204,229),false);su.setPadding(0,dp(4),0,0);inf.addView(su);top.addView(inf);boolean fav=pref.getBoolean(x.n,false);TextView star=t(fav?"★":"☆",28,fav?Color.rgb(255,211,80):Color.rgb(145,165,192),true);star.setGravity(17);star.setLayoutParams(new LinearLayout.LayoutParams(dp(46),dp(46)));star.setOnClickListener(v->{pref.edit().putBoolean(x.n,!pref.getBoolean(x.n,false)).apply();render();});top.addView(star);c.addView(top);TextView d=t(x.d,13,Color.rgb(169,189,216),false);d.setPadding(0,dp(12),0,dp(9));c.addView(d);LinearLayout bot=new LinearLayout(this);bot.setGravity(Gravity.CENTER_VERTICAL);bot.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView b=t(x.b,12,Color.rgb(119,255,201),true);b.setGravity(17);b.setPadding(dp(10),dp(4),dp(10),dp(4));b.setBackgroundResource(R.drawable.bg_badge_green);bot.addView(b);TextView note=t(x.x,12,Color.rgb(143,169,204),false);note.setPadding(dp(12),0,dp(12),0);note.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));bot.addView(note);bot.addView(t("باز کردن  ←",13,Color.rgb(49,215,255),true));c.addView(bot);c.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(x.u)));}catch(Exception e){Toast.makeText(this,"مرورگر پیدا نشد",1).show();}});return c;}
}
